// ignore_for_file: non_constant_identifier_names

import 'buffer.dart';
import 'frame.dart';
import 'node.dart';
import 'renderables.dart';

T _attachChildren<T extends BaseRenderable>(
  T parent,
  List<BaseRenderable> children,
) {
  for (final child in children) {
    parent.add(child);
  }
  return parent;
}

typedef RenderableFactory<T extends BaseRenderable> = T Function();

/// Instantiates a renderable from either:
/// - an existing [BaseRenderable] instance, or
/// - a [RenderableFactory] callback.
///
/// This keeps declarative composition ergonomic in Dart even though construct
/// helpers already return concrete renderables.
T instantiate<T extends BaseRenderable>(Object renderableOrFactory) {
  if (renderableOrFactory is BaseRenderable) {
    if (renderableOrFactory is T) {
      return renderableOrFactory;
    }
    throw ArgumentError(
      'instantiate expected $T but received ${renderableOrFactory.runtimeType}.',
    );
  }

  if (renderableOrFactory is BaseRenderable Function()) {
    final created = renderableOrFactory();
    if (created is T) {
      return created;
    }
    throw ArgumentError(
      'instantiate factory produced ${created.runtimeType}, expected $T.',
    );
  }

  throw ArgumentError(
    'instantiate expected a BaseRenderable or BaseRenderable Function().',
  );
}

/// Annotates [renderable] so selected APIs are routed to descendants by `id`.
///
/// For example, `delegate({'add': 'slot'}, node)` routes `add(...)` calls to
/// the descendant with id `slot` when present.
DelegatedRenderable<T> delegate<T extends BaseRenderable>(
  Map<String, String> mapping,
  T renderable,
) {
  return DelegatedRenderable<T>(root: renderable, delegates: mapping);
}

BoxRenderable Box({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  TuiLayoutDirection layoutDirection = TuiLayoutDirection.column,
  TuiWrap wrap = TuiWrap.noWrap,
  TuiJustify justify = TuiJustify.start,
  TuiAlign align = TuiAlign.stretch,
  bool border = false,
  String? title,
  int padding = 0,
  int? paddingX,
  int? paddingY,
  int? paddingLeft,
  int? paddingTop,
  int? paddingRight,
  int? paddingBottom,
  TuiStyle style = TuiStyle.plain,
  TuiStyle borderStyle = const TuiStyle(foreground: TuiColor.cyan),
  List<BaseRenderable> children = const <BaseRenderable>[],
}) {
  return _attachChildren(
    BoxRenderable(
      id: id,
      width: width,
      height: height,
      widthPercent: widthPercent,
      heightPercent: heightPercent,
      minWidth: minWidth,
      maxWidth: maxWidth,
      minHeight: minHeight,
      maxHeight: maxHeight,
      margin: margin,
      marginX: marginX,
      marginY: marginY,
      marginLeft: marginLeft,
      marginTop: marginTop,
      marginRight: marginRight,
      marginBottom: marginBottom,
      left: left,
      top: top,
      flexGrow: flexGrow,
      layoutDirection: layoutDirection,
      wrap: wrap,
      justify: justify,
      align: align,
      border: border,
      title: title,
      padding: padding,
      paddingX: paddingX,
      paddingY: paddingY,
      paddingLeft: paddingLeft,
      paddingTop: paddingTop,
      paddingRight: paddingRight,
      paddingBottom: paddingBottom,
      style: style,
      borderStyle: borderStyle,
    ),
    children,
  );
}

GroupRenderable Group({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  TuiLayoutDirection layoutDirection = TuiLayoutDirection.column,
  TuiWrap wrap = TuiWrap.noWrap,
  TuiJustify justify = TuiJustify.start,
  TuiAlign align = TuiAlign.stretch,
  TuiStyle style = TuiStyle.plain,
  List<BaseRenderable> children = const <BaseRenderable>[],
}) {
  return _attachChildren(
    GroupRenderable(
      id: id,
      width: width,
      height: height,
      widthPercent: widthPercent,
      heightPercent: heightPercent,
      minWidth: minWidth,
      maxWidth: maxWidth,
      minHeight: minHeight,
      maxHeight: maxHeight,
      margin: margin,
      marginX: marginX,
      marginY: marginY,
      marginLeft: marginLeft,
      marginTop: marginTop,
      marginRight: marginRight,
      marginBottom: marginBottom,
      left: left,
      top: top,
      flexGrow: flexGrow,
      layoutDirection: layoutDirection,
      wrap: wrap,
      justify: justify,
      align: align,
      style: style,
    ),
    children,
  );
}

ScrollBoxRenderable ScrollBox({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  TuiLayoutDirection layoutDirection = TuiLayoutDirection.column,
  TuiWrap wrap = TuiWrap.noWrap,
  TuiJustify justify = TuiJustify.start,
  TuiAlign align = TuiAlign.stretch,
  bool border = false,
  String? title,
  int padding = 0,
  int? paddingX,
  int? paddingY,
  int? paddingLeft,
  int? paddingTop,
  int? paddingRight,
  int? paddingBottom,
  int scrollOffset = 0,
  int scrollStep = 1,
  int fastScrollStep = 5,
  TuiStyle style = TuiStyle.plain,
  TuiStyle borderStyle = const TuiStyle(foreground: TuiColor.cyan),
  List<BaseRenderable> children = const <BaseRenderable>[],
}) {
  return _attachChildren(
    ScrollBoxRenderable(
      id: id,
      width: width,
      height: height,
      widthPercent: widthPercent,
      heightPercent: heightPercent,
      minWidth: minWidth,
      maxWidth: maxWidth,
      minHeight: minHeight,
      maxHeight: maxHeight,
      margin: margin,
      marginX: marginX,
      marginY: marginY,
      marginLeft: marginLeft,
      marginTop: marginTop,
      marginRight: marginRight,
      marginBottom: marginBottom,
      left: left,
      top: top,
      flexGrow: flexGrow,
      layoutDirection: layoutDirection,
      wrap: wrap,
      justify: justify,
      align: align,
      border: border,
      title: title,
      padding: padding,
      paddingX: paddingX,
      paddingY: paddingY,
      paddingLeft: paddingLeft,
      paddingTop: paddingTop,
      paddingRight: paddingRight,
      paddingBottom: paddingBottom,
      scrollOffset: scrollOffset,
      scrollStep: scrollStep,
      fastScrollStep: fastScrollStep,
      style: style,
      borderStyle: borderStyle,
    ),
    children,
  );
}

TextRenderable Text({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required String content,
  TuiStyle style = TuiStyle.plain,
}) {
  return TextRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    content: content,
    style: style,
  );
}

InputRenderable Input({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  String value = '',
  String placeholder = '',
  TuiStyle style = TuiStyle.plain,
  TuiStyle focusedStyle = const TuiStyle(
    foreground: TuiColor.black,
    background: TuiColor.white,
  ),
  TuiStyle placeholderStyle = const TuiStyle(foreground: TuiColor.cyan),
}) {
  return InputRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    value: value,
    placeholder: placeholder,
    style: style,
    focusedStyle: focusedStyle,
    placeholderStyle: placeholderStyle,
  );
}

TextareaRenderable Textarea({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  String value = '',
  String placeholder = '',
  int scrollTop = 0,
  TuiStyle style = TuiStyle.plain,
  TuiStyle focusedStyle = const TuiStyle(
    foreground: TuiColor.black,
    background: TuiColor.white,
  ),
  TuiStyle placeholderStyle = const TuiStyle(foreground: TuiColor.cyan),
}) {
  return TextareaRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    value: value,
    placeholder: placeholder,
    scrollTop: scrollTop,
    style: style,
    focusedStyle: focusedStyle,
    placeholderStyle: placeholderStyle,
  );
}

SelectRenderable Select({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required List<String> options,
  int selectedIndex = 0,
  TuiStyle style = TuiStyle.plain,
  TuiStyle selectedStyle = const TuiStyle(
    foreground: TuiColor.black,
    background: TuiColor.green,
    bold: true,
  ),
}) {
  return SelectRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    options: options,
    selectedIndex: selectedIndex,
    style: style,
    selectedStyle: selectedStyle,
  );
}

TabSelectRenderable TabSelect({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required List<String> options,
  int selectedIndex = 0,
  TuiStyle style = TuiStyle.plain,
  TuiStyle selectedStyle = const TuiStyle(
    foreground: TuiColor.black,
    background: TuiColor.green,
    bold: true,
  ),
  String separator = ' | ',
}) {
  return TabSelectRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    options: options,
    selectedIndex: selectedIndex,
    style: style,
    selectedStyle: selectedStyle,
    separator: separator,
  );
}

ASCIIFontRenderable ASCIIFont({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required String text,
  int letterSpacing = 1,
  TuiStyle style = TuiStyle.plain,
}) {
  return ASCIIFontRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    content: text,
    letterSpacing: letterSpacing,
    style: style,
  );
}

FrameBufferRenderable FrameBuffer({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required OptimizedBuffer buffer,
  bool transparent = false,
}) {
  return FrameBufferRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    buffer: buffer,
    transparent: transparent,
  );
}

MarkdownRenderable Markdown({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required String markdown,
  TuiStyle style = TuiStyle.plain,
}) {
  return MarkdownRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    markdown: markdown,
    style: style,
  );
}

CodeRenderable Code({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required String code,
  TuiStyle style = TuiStyle.plain,
}) {
  return CodeRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    code: code,
    style: style,
  );
}

DiffRenderable Diff({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required String previous,
  required String next,
  TuiStyle style = TuiStyle.plain,
}) {
  return DiffRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    previous: previous,
    next: next,
    style: style,
  );
}

LineNumberRenderable LineNumber({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  required List<String> lines,
  TuiStyle style = TuiStyle.plain,
}) {
  return LineNumberRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    lines: lines,
    style: style,
  );
}

ScrollbarRenderable Scrollbar({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  double value = 0,
  double thumbRatio = 0.2,
  double step = 0.05,
  double fastStep = 0.2,
  bool vertical = true,
  TuiStyle trackStyle = const TuiStyle(foreground: TuiColor.cyan),
  TuiStyle thumbStyle = const TuiStyle(foreground: TuiColor.white, bold: true),
}) {
  return ScrollbarRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    value: value,
    thumbRatio: thumbRatio,
    step: step,
    fastStep: fastStep,
    vertical: vertical,
    trackStyle: trackStyle,
    thumbStyle: thumbStyle,
  );
}

ScrollbarRenderable ScrollBar({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  double value = 0,
  double thumbRatio = 0.2,
  double step = 0.05,
  double fastStep = 0.2,
  bool vertical = true,
  TuiStyle trackStyle = const TuiStyle(foreground: TuiColor.cyan),
  TuiStyle thumbStyle = const TuiStyle(foreground: TuiColor.white, bold: true),
}) {
  return Scrollbar(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    value: value,
    thumbRatio: thumbRatio,
    step: step,
    fastStep: fastStep,
    vertical: vertical,
    trackStyle: trackStyle,
    thumbStyle: thumbStyle,
  );
}

SliderRenderable Slider({
  String? id,
  int? width,
  int? height,
  double? widthPercent,
  double? heightPercent,
  int? minWidth,
  int? maxWidth,
  int? minHeight,
  int? maxHeight,
  int margin = 0,
  int? marginX,
  int? marginY,
  int? marginLeft,
  int? marginTop,
  int? marginRight,
  int? marginBottom,
  int? left,
  int? top,
  double flexGrow = 1,
  double min = 0,
  double max = 100,
  double value = 0,
  double step = 1,
  bool vertical = false,
  TuiStyle trackStyle = const TuiStyle(foreground: TuiColor.cyan),
  TuiStyle thumbStyle = const TuiStyle(foreground: TuiColor.white, bold: true),
}) {
  return SliderRenderable(
    id: id,
    width: width,
    height: height,
    widthPercent: widthPercent,
    heightPercent: heightPercent,
    minWidth: minWidth,
    maxWidth: maxWidth,
    minHeight: minHeight,
    maxHeight: maxHeight,
    margin: margin,
    marginX: marginX,
    marginY: marginY,
    marginLeft: marginLeft,
    marginTop: marginTop,
    marginRight: marginRight,
    marginBottom: marginBottom,
    left: left,
    top: top,
    flexGrow: flexGrow,
    min: min,
    max: max,
    value: value,
    step: step,
    vertical: vertical,
    trackStyle: trackStyle,
    thumbStyle: thumbStyle,
  );
}
